---
title: "DINÂMICA HIDRO-BIOGEOMORFOLÓGICA DE RIOS INTERMITENTES – O IMPACTO DO PROJETO
  DE INTEGRAÇÃO DO RIO SÃO FRANCISCO (PISF) NA DINÂMICA E ESTRUTURA FLUVIAL"
author: "Gabriel de Jesus Pereira"
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Resumo

Obras hídricas, como o Projeto de Integração do Rio São Francisco (PISF), afetam diretamente a dinâmica hidrológica dessas áreas, modificando a dinâmica bio-geomorfológica. A análise dos impactos bio-geomorfológicos gerados por obras desse porte são essenciais para gerenciamento adequado dessas áreas. Desse, o presente projeto pretende analisar os impactos bio-geomorfológica gerados pelo PISF, para tal serão analisados e comparados trechos fluviais da bacia do Alto Curso do Rio Paraíba, impactado pelo PISF e não impactados. Para tal, será analisada a dinâmica hidro-biogeomorfológica da bacia, incluindo a análise da conectividade e do impacto de sazonalidade da vegetação na dinâmica superficial. Em um segundo momento, será analisado a correlação entre precipitação e hidrologia dos canais, no período anterior e posterior ao PISF. Posteriormente, ambos os rios terão suas características e comportamentos hidro-biogeomorfológico analisados, visando a classificação dos Estilos Fluviais e Conectividade da Paisagem. A partir dessas etapas serão selecionados trechos para o monitoramento e anãlise detalhada. Assim, serão identificados quais modificações bio-geomorfológicas foram geradas pelo PISF. Para tal, serão utilizados dados de coleta de sedimento, dados de campo e levantamentos aerofotogramétricos; visando diferencias as mudanças e evolução de trechos impactados e não impactados pelo PISF. Assim, será possível entender o impacto do PISF, indicando modificações prováveis e gerando dados que poderão subsidias a gestão dessas e de outras áreas semelhantes.

# Abstract

Water works, such as the São Francisco River Integration Project (PISF), directly affect the hydrological dynamics of these areas, modifying the bio-geomorphological dynamics. The analysis of the bio-geomorphological impacts generated by works of this size are essential for the proper management of these areas. In this way, the present project intends to analyze the bio-geomorphological impacts generated by the PISF, for that will be analyzed and compared river stretches of the basin of the Alto Curso do Rio Paraíba, impacted by the PISF and not impacted. To this end, the hydro-biogeomorphological dynamics of the basin will be analyzed, including the analysis of connectivity and the impact of vegetation seasonality on surface dynamics. In a second moment, the correlation between precipitation and channel hydrology will be analyzed, in the period before and after the PISF. Subsequently, both rivers will have their hydro-biogeomorphological characteristics and behaviors analyzed, aiming at the classification of Fluvial Styles and Landscape Connectivity. From these steps, sections will be selected for monitoring and detailed analysis. Thus, it will be identified which bio-geomorphological modifications were generated by PISF. To this end, sediment collection data, field data and aerophotogrammetric surveys will be used; aiming to differentiate the changes and evolution of stretches impacted and not impacted by the PISF. Thus, it will be possible to understand the impact of the PISF, indicating likely changes and generating data that may support the management of these and other similar areas.


# 1 Introdução

Este relátorio é fruto do trabalho desenvolvido enquanto bolsista PIBIC na modalidade Iniciação Científica, sob orientação do professor Jonas Otaviano Praça de Souza. A ideia central do projeto consiste em analisar as diferenças processuais e morfológicas geradas pela operação do Projeto de Integração do Rio São Francisco no Alto Curso do Rio Paraíba. Pois assim será possível ampliar as discussões sobre a dinâmica e sua relação com as características e dinâmica inter e intra-anual da vegetação de Caatinga. Como objetivo da pesquisa, buscou-se também identificar vários arranjos de vegetação de Caatinga nos cenários geológicos cristalino e sedimentar, analisar o comportamento da densidade da biomassa durante uma década, coletar e analisar os dados de precipitação dos postos pluviométricos da área durante uma década, levando em consideração anos secos, chuvosos e habituais. Ainda, procurou-se também entender a relação entre essas mudanças na biomassa e a precipitação. Essa abordagem visa contribuir para uma compreensão mais profunda da dinâmica e das interações da vegetação de Caatinga, explorando as influências da operação do Projeto de Integração do Rio São Francisco e das variações climáticas. O entedimento da dinâmica superficial do sistema fluvial é o ponto de partida da análise, visto que informações sobre a dinâmica hidrogeomorfógica da rede de drenagem, bem como o impacto da sazonalidade da relação chuva/vegetação na dinâmica hidrológica e dedimentológica. Após essa análise inicial será possível identificar como as mudanças processuais, de cunho antrópico, geram modificações na estrutura e morfologia fluvial (CHRISTOFOLETTI, 1999), assim se faz necessário prever as modificações e monitorar-lás, ao se intervenções de grande magnitude.

# Fundamentação teórica

Para prosseguir com a pesquisa, foi necessário entender sobre conceitos básicos sobre o semiárido e semiárido brasileiro. Assim, vimos que ambientes semiáridos e ambientes sub-úmidos, apresentam características processuais diferenciadas em relação aos ambientes úmidos. Essa diferenciação é resultado da diferença dos inputs de energia no sistema, em específico da precipitação (SOUZA e ALMEIDA, 2015). Ainda, nos semiáridos é comum a retroalimentação positiva, onde surge uma acelerada degradação dos solos, em decorrência do uso (DREW, 2005; SACO, WILGOOSE e HANCOCK, 2007). Nas terras secas o escoamento superficial representa a contribuição de massa e energia para a rede de drenagem e estímulo para processos fluviais, como também o trabalho geomorfológico exercido pelo escoamento está relacionado aos processos fluviais pelo fornecimento de sedimentos (GRAF, 1988), sendo a vegetação o fator mais sensitivo a modificações naturais e principalmente antrópicas. Assim analisando as modificações dos padrões e distribuição da vegetação no semiárido pode-se ter indicações da variação do escoamento superficial, e consequentemente da mudança nas fontes de sedimento e das áreas de sedimentação. 

Falar sobre o semiárido e o semia´rido brasileiro
Rios no semiárido – regimes hidrológicos (perene, intermitente e efêmero) focando nos rios intermitentes 
Morfologia do rio intermitente e relação com a vegetação ripária.
PISF e modificação nos rios receptores.


# 2 Objetivos

## 2.1 Objetivo Geral

O propósito principal da pesquisa foi analisar o comportamento hidrológico, ecológico e geomorfológico do Alto Curso do Rio Paraíba. Ainda, buscou-se também compreender as diferenças processuais geradas em decorrência da implementação do projeto de Integração do Rio São Francisco nessa mesma área.

## 2.2 Objetivos Específicos

Os objetivos específicos da pesquisa se consistiram em classificar os diferentes estilos fluviais e analisar a conectividade  da paisagem dos trechos, avaliar o comportamento da sazonalidade da vegetação em relação aos eventos de precipitação, relacionar o impacto eventos extremos da precipitação com a sazonalidade da densidade da vegetação, analisar a dinâmica fluvial no alto curso do Rio Paraíba e sua variação após a implementação do PISF e identificar os efeitos das mudanças hidrológicas sobre os padrões biogeomorfológicos das margens.

# Materiais e Métodos

O projeto foi desenvolvido junto ao Grupo de Estudos de Sistemas Fluviais Semiáridos (GEAFS) e também contou com o Laboratório de Estudos Fluviais (LEF). Para o desenvolvimento das atividades foi preciso fazer a coleta de dados de chuva e vazão, utilizando a plataforma Hidroweb, que faz parte Agência Nacional de Águas e Saneamento Básico (ANA). Para prosseguir com a análise dos dados, foi utilizado a linguagem de programação Python, utilizando Jupyter Lab. Utilizando a mesma, foram realizados transformações no banco de dados para que representasse, por exemplo, a variável Ano apenas como uma coluna, para que os anos não fossem representados como variáveis do banco de dados. Foram também calculados a máxima e mínima da precipitação anual, a média anual de precipitação, a máxima e mínima de dias de chuva no ano. O mesmo foi feito para os dados de vazão. Após os cálculos dessas variáveis, foram coletados mais dados, agora da plataforma Map Biomas. Esses dados se tratam de hectares de floresta, agricultura, mangue, formação florestal, formação savância. Assim, foram realizado o cruzamento dos dados de chuva da plataforma Hidroweb com os dados da plataforma Map Biomas. Após o cruzamento desses dados, utilizando-se o a variável ano como base, foram comparados a máxima de chuva por ano e os hectares de floresta, formação florestal, formação savânica, mangue e agricultura. Dessa forma, seria possível cálcular uma correlação de Pearson para se analisar a relação entre essas duas variáveis. Todo o estudo foi realizado com estações do município de Piancó - PB.   

# Resultados e discussão



# Conclusão



# Referências bibliográficas